---
name: Build FFMPEG

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build FFMPEG
    runs-on: ubuntu-latest
    steps:
      - name: "Install Dependencies"
        run: |
          ./Prep_System.sh
      - name: "Build FFMPEG"
        run: |
          ./Cross-Compile_FFMPEG.sh
