---
name: Build FFMPEG

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build FFMPEG
    runs-on: ubuntu-latest
    timeout-minutes: 75
    steps:
      - uses: actions/checkout@v4
      - name: "Install Dependencies"
        run: |
          sudo ./Prep_System.sh
      - name: "Build FFMPEG"
        run: |
          ./Cross-Compile_FFMPEG.sh
      - name: 'Verify Binaries Created'
        uses: thebinaryfelix/check-file-existence-action@2.0.0 # check the latest release
        with:
          files: './ffmpeg_install/bin/ffmpeg.exe, ./ffmpeg_install/bin/ffprobe.exe, ./ffmpeg_install/bin/ffplay.exe'
