---
name: Build FFMPEG

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build FFMPEG
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: "Install Dependencies"
        run: |
          sudo ./Prep_System.sh
      - name: "Build FFMPEG"
        run: |
          ./Cross-Compile_FFMPEG.sh
